steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/progretech-mesh:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/progretech-mesh:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - progretech-mesh
      - --image=us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/progretech-mesh:$COMMIT_SHA
      - --region=us-east1
      - --project=$PROJECT_ID
      - --max-instances=1
      - --timeout=3600
      - --quiet

images:
  - us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/progretech-mesh:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
