steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/progretech-mesh:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/progretech-mesh:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - progretech-mesh
      - --image=gcr.io/$PROJECT_ID/progretech-mesh:$COMMIT_SHA
      - --region=us-east1
      - --project=$PROJECT_ID
      - --quiet

images:
  - gcr.io/$PROJECT_ID/progretech-mesh:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
