$ErrorActionPreference = "Stop"

$env:MESH_RUNTIME_ADAPTER = "openclaw"
if (-not $env:OPENCLAW_BIN) { $env:OPENCLAW_BIN = "$HOME/.openclaw/bin/openclaw" }
if (-not $env:OPENCLAW_CWD) { $env:OPENCLAW_CWD = "$HOME/Rend" }
if (-not $env:OPENCLAW_TIMEOUT) { $env:OPENCLAW_TIMEOUT = "180" }

Write-Host "Mesh runtime adapter: $env:MESH_RUNTIME_ADAPTER"
Write-Host "OpenClaw binary:      $env:OPENCLAW_BIN"
Write-Host "OpenClaw cwd:         $env:OPENCLAW_CWD"
Write-Host ""
Write-Host "Now run the Pair Gateway command generated by Mesh in this same shell."
