#!/usr/bin/env bash
set -euo pipefail

export MESH_RUNTIME_ADAPTER=openclaw
export OPENCLAW_BIN="${OPENCLAW_BIN:-$HOME/.openclaw/bin/openclaw}"
export OPENCLAW_CWD="${OPENCLAW_CWD:-$HOME/Rend}"
export OPENCLAW_TIMEOUT="${OPENCLAW_TIMEOUT:-180}"

echo "Mesh runtime adapter: ${MESH_RUNTIME_ADAPTER}"
echo "OpenClaw binary:      ${OPENCLAW_BIN}"
echo "OpenClaw cwd:         ${OPENCLAW_CWD}"
echo
echo "Now run the Pair Gateway command generated by Mesh in this same shell."
